<Project>
  <PropertyGroup>
    <Authors>Stangherlin Enrico</Authors>
    <Company>StangaNet</Company>
    <Copyright>Copyright (c) StangaNet. All rights reserved.</Copyright>
    <PackageProjectUrl>https://github.com/StangaNet/StangaNetLib.Core</PackageProjectUrl>
    <RepositoryUrl>$(PackageProjectUrl)</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageOutputPath>$(MSBuildThisFileDirectory)artifacts</PackageOutputPath>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;NU1903</NoWarn>
  </PropertyGroup>
</Project>
