name: .NET CI

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: StangaNet/.github/.github/workflows/dotnet-lib.yml@main
    with:
      library-name: 'StangaNetLib.Core'
      artifact-name: 'stanganetlib-core-nuget'
    secrets: inherit
